[workspace]
members = ["crates/chip8"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
# Tell `rustc` to optimize for small code size.
opt-level = "s"
